Documentation:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Rails:
  Enabled: true
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - !ruby/regexp /old_and_unused\.rb$/
